# Generated by Django 5.0.2 on 2025-01-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paperanalysis_data_analysis_errors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperanalysis',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='papers.paper'),
        ),
    ]
