# Generated by Django 5.0.2 on 2025-01-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_paperanalysis_paper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperanalysis',
            old_name='methdology_errors',
            new_name='methodology_errors',
        ),
    ]
