# Generated by Django 5.0.2 on 2025-01-23 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_rename_methdology_errors_paperanalysis_methodology_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='input_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='output_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='papersummary',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='papers.paper'),
        ),
    ]
