# Generated by Django 5.1.5 on 2025-02-03 08:27

import django.db.models.deletion
import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paper_input_tokens_paper_output_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(max_length=255, storage=papers.models.PaperFileS3Storage, upload_to=papers.models.get_paper_s3_file_path),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='PaperSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_type', models.CharField(choices=[('paper_title', 'Paper Title'), ('child_summary', 'Child Summary'), ('college_summary', 'College Summary'), ('phd_summary', 'Phd Summary')], max_length=20)),
                ('voice_type', models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('coral', 'Coral'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('sage', 'Sage'), ('shimmer', 'Shimmer')], defaul>
                ('audio_file', models.FileField(blank=True, null=True, storage=papers.models.SpeechFileS3Storage, upload_to=papers.models.get_speech_s3_file_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('generation_cost', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('content_source', models.TextField(blank=True, null=True)),
                ('allowed_user_ids', models.JSONField(blank=True, default=list, help_text='List of user IDs that have purchased access to this speech')),
                ('payment_records', models.JSONField(blank=True, default=list, help_text="Stores payment metadata in format [{'user_id': '...', 'payment_ref': '...', 'date': '...'}]")),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='papers.paper')),
            ],
            options={
                'indexes': [models.Index(fields=['allowed_user_ids'], name='user_access_idx')],
            },
        ),
    ]
