# Generated by Django 5.0.2 on 2025-01-30 15:16

import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paper_input_tokens_paper_output_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(max_length=255, storage=papers.models.PaperFileS3Storage, upload_to=papers.models.get_paper_s3_file_path),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
