# Generated by Django 5.1.4 on 2025-01-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
